kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: scottyhardy/docker-wine
    commands:
      - wget python.org/ftp/python/3.13.0/python-3.13.0.exe
      - wine python-3.13.0.exe -m pip install -r requirements.txt
      - wine python-3.13.0.exe -m pip install pyinstaller

trigger:
  ref:
    - refs/heads/wine
