kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: scottyhardy/docker-wine
    commands:
      - wget https://www.python.org/ftp/python/3.13.0/python-3.13.0-embed-amd64.zip
      - unzip python-3.13.0-embed-amd64.zip
      - wine python.exe -m pip install -r requirements.txt
      - wine python.exe -m pip install pyinstaller

trigger:
  ref:
    - refs/heads/wine
